let _constants = {
  CALENDAR: {
    TIME_OPTIONS: {
      day: "Day",
      week: "Week",
      month: "Month",
      year: "Year",
      fourDays: "4 Days",
    },
    WEEKDAYS: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    WEEKDAYS_INDEX: {
      SUNDAY: 0,
      MONDAY: 0,
      TUESDAY: 1,
      WEDNESDAY: 2,
      THURSDAY: 3,
      FRIDAY: 4,
      SATURDAY: 5,
      SUNDAY: 6,
    },
    MONTHS: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    MONTHS_INDEX: {
      JANUARY: 0,
      FEBRURARY: 1,
      MARCH: 2,
      APRIL: 3,
      MAY: 4,
      JUNE: 5,
      JULY: 6,
      AUGUST: 7,
      SEPTEMBER: 8,
      OCTOBER: 9,
      NOVEMBER: 10,
      DECEMBER: 11,
    },
  },
};

export default _constants;
